### ISSUE TITLE
"previous-track" doesn't apply color value to whole icon

### ISSUE THREAD

**Issue by rockneverdies55** [ivanoff/react-native-ico-material-design#1]
"previous-track" icon doesn't apply the color value to whole thing. 

```
import Icon from 'react-native-ico-material-design';

return <Icon name="previous-track" height={34} width={34} color="#CC6B4B" />;
```

The left part of the icon is black and the right part is #CC6B4B.

**Comment by ivanoff** [comment]
Could you try

```
colors={{ "<g>": "<g fill=\"#CC6B4B\">" }}
```

**Comment by ivanoff** [comment]
![image](https://github.com/ivanoff/react-native-ico-material-design/assets/304105/10b98fcf-5aca-423e-bda9-5da590a74427)

**Comment by ivanoff** [comment]
It seems like a hack, but the material-design icons don't have a black background.

**Comment by ivanoff** [comment]
```
<Icon name="previous-track" height={34} width={34} colors={{ '<g': "<g fill=\"#CC6B4B\" " }} />
```

**Comment by rockneverdies55** [comment]
> <Icon name="previous-track" height={34} width={34} colors={{ '<g': "<g fill=\"#CC6B4B\" " }} />

Seems to solve the problem for me. Thank you very much.
